#!/usr/bin/python

import telnetlib as tn
import getpass
import subprocess as subp
import re
from time import sleep

def connectivity(ip_rtr):
    print('\n','*'*60)
    print ("The ROuter's IP:=",ip_rtr)
    o=subp.check_output(['ping',ip_rtr,'-c','5']).decode('utf-8')
    
    expr=r'([0-9]+)(% packet loss)'
    inp=re.search(expr,o)
    if inp.group(1) == '0':
       print ('NO PACKET LOSS. CONNECTIVTITY IS SECURE...')
       return True
    else:
       print (inp.groups())
       print ('PACKET LOSS OF:-',inp.group(1))
       return False
     

def tel_to_rtr(ip_rtr,skt_cont):
    port=5000
    uname='test1'
    print ('PLEASE PROVIDE THE PASSWD FOR USER TEST1 TO LOGIN TO RTR, BE READY \n\n') 
    sleep(10)
    passwd=getpass.getpass()
    host=ip_rtr
    print ('LOGIN SCREEN :-',skt_cont) 
    a=skt_cont.read_until("Username: ")
    a1=skt_cont.write(uname+"\n")

    b=skt_cont.read_until("Password: ")
    b1=skt_cont.write(passwd+"\n")
    '''
    print ('a:-',a)
    print ('a1:-',a1)
    print ('b:-',b)
    print ('b1:-',b1)
    '''
    c=skt_cont.read_until("gns3-r1#")
    #print ('c:-',c)
    skt_cont.write("conf t\n")
    skt_cont.write("int lo0\n")
    skt_cont.write("ip address 1.1.1.1 255.255.255.255\n")
    skt_cont.write("no shut\n")
    skt_cont.write("end\n")
    skt_cont.write("show ip interface brief\n")
    skt_cont.write("exit\n")
    print(skt_cont.read_all())
    skt_cont.close()

#ip_rtr=input('PLEASE ENTER THE IP ADDRESS OF THE RTR:-')
ip_rtr='192.168.168.1'

output=connectivity(ip_rtr)

if (output):
   
   skt_cont=tn.Telnet(ip_rtr)
   tel_to_rtr(ip_rtr,skt_cont)
else:
   print ('SCRIPT FAILED. COZ OF PKT LOSS...')
